apiVersion: v1
kind: Service
metadata:
  name: ccg-mysql-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: "mysql-port"
      protocol: "TCP"
      port: 3306
      targetPort: 3306
  selector:
    app: ccg-mysql